"""Caddy config generator for tunneled services."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Template

if TYPE_CHECKING:
    from tunnelctl.config import EndpointConfig, TunnelConfig

logger = logging.getLogger(__name__)

CADDYFILE_TEMPLATE = Template("""\
# Generated by tunnelctl - do not edit manually
{% for tunnel in http_tunnels %}
{{ tunnel.subdomain }}.{{ domain }} {
    reverse_proxy 127.0.0.1:{{ tunnel.remote_port }}
}
{% endfor %}
""")


class CaddyConfigGenerator:
    """Generates Caddyfile for tunneled HTTP services.

    Caddy handles TLS automatically via Let's Encrypt.
    TCP tunnels are accessed directly by port (no Caddy proxy needed).
    """

    def __init__(self, endpoint: EndpointConfig) -> None:
        self.endpoint = endpoint
        self.config_path = Path(
            endpoint.proxy.config_path.replace("nginx", "caddy")
            if "nginx" in endpoint.proxy.config_path
            else endpoint.proxy.config_path
        )
        self.domain = endpoint.proxy.http_domain.lstrip("*.")

    def generate(self, tunnels: list[TunnelConfig]) -> str:
        """Generate Caddyfile content."""
        http_tunnels = []
        for t in tunnels:
            if t.endpoints and self.endpoint.name not in t.endpoints:
                continue
            if t.protocol == "http" and t.subdomain:
                http_tunnels.append({
                    "name": t.name,
                    "subdomain": t.subdomain,
                    "remote_port": t.remote_port,
                })

        return CADDYFILE_TEMPLATE.render(
            http_tunnels=http_tunnels, domain=self.domain
        )

    def write(self, tunnels: list[TunnelConfig]) -> None:
        """Generate and write Caddyfile to disk."""
        config = self.generate(tunnels)
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(config)
        logger.info("Wrote Caddyfile to %s", self.config_path)

    def apply(self, tunnels: list[TunnelConfig]) -> bool:
        """Generate and write Caddyfile. Caddy auto-reloads on file change."""
        self.write(tunnels)
        # Caddy watches its config file and auto-reloads
        return True
