"""NGINX config generator for tunneled services."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Template

if TYPE_CHECKING:
    from tunnelctl.config import EndpointConfig, TunnelConfig

logger = logging.getLogger(__name__)

HTTP_SERVER_TEMPLATE = Template("""\
# Generated by tunnelctl - do not edit manually
{% for tunnel in http_tunnels %}
server {
    listen 80;
    server_name {{ tunnel.subdomain }}.{{ domain }};

    location / {
        proxy_pass http://127.0.0.1:{{ tunnel.remote_port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
{% endfor %}
""")

STREAM_TEMPLATE = Template("""\
# Generated by tunnelctl - TCP stream blocks
{% for tunnel in tcp_tunnels %}
# {{ tunnel.name }}: {{ tunnel.internal_host }}:{{ tunnel.internal_port }}
server {
    listen {{ tunnel.listen_port }};
    proxy_pass 127.0.0.1:{{ tunnel.remote_port }};
}
{% endfor %}
""")


class NginxConfigGenerator:
    """Generates NGINX configuration for tunneled services."""

    def __init__(self, endpoint: EndpointConfig) -> None:
        self.endpoint = endpoint
        self.config_path = Path(endpoint.proxy.config_path)
        self.stream_config_path = self.config_path.with_suffix(".stream.conf")
        # Strip leading wildcard from domain: "*.example.com" -> "example.com"
        self.domain = endpoint.proxy.http_domain.lstrip("*.")

    def generate(self, tunnels: list[TunnelConfig]) -> tuple[str, str]:
        """Generate HTTP and stream configs. Returns (http_config, stream_config)."""
        http_tunnels = []
        tcp_tunnels = []

        for t in tunnels:
            # Check this tunnel targets this endpoint
            if t.endpoints and self.endpoint.name not in t.endpoints:
                continue

            if t.protocol == "http" and t.subdomain:
                http_tunnels.append({
                    "name": t.name,
                    "subdomain": t.subdomain,
                    "remote_port": t.remote_port,
                    "internal_host": t.internal_host,
                    "internal_port": t.internal_port,
                })
            elif t.protocol == "tcp":
                tcp_tunnels.append({
                    "name": t.name,
                    "remote_port": t.remote_port,
                    "listen_port": t.remote_port,  # expose on same port
                    "internal_host": t.internal_host,
                    "internal_port": t.internal_port,
                })

        http_config = HTTP_SERVER_TEMPLATE.render(
            http_tunnels=http_tunnels, domain=self.domain
        )
        stream_config = STREAM_TEMPLATE.render(tcp_tunnels=tcp_tunnels)
        return http_config, stream_config

    def write(self, tunnels: list[TunnelConfig]) -> None:
        """Generate and write configs to disk."""
        http_config, stream_config = self.generate(tunnels)

        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(http_config)
        logger.info("Wrote HTTP config to %s", self.config_path)

        if stream_config.strip():
            self.stream_config_path.write_text(stream_config)
            logger.info("Wrote stream config to %s", self.stream_config_path)

    def test(self) -> bool:
        """Run nginx -t to validate config."""
        try:
            result = subprocess.run(
                ["nginx", "-t"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                logger.error("nginx config test failed: %s", result.stderr)
                return False
            return True
        except FileNotFoundError:
            logger.error("nginx not found in PATH")
            return False

    def reload(self) -> bool:
        """Reload nginx after config change."""
        cmd = self.endpoint.proxy.reload_command.split()
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
            if result.returncode != 0:
                logger.error("nginx reload failed: %s", result.stderr)
                return False
            logger.info("NGINX reloaded successfully")
            return True
        except Exception as e:
            logger.error("Failed to reload nginx: %s", e)
            return False

    def apply(self, tunnels: list[TunnelConfig]) -> bool:
        """Generate, test, and reload NGINX config."""
        self.write(tunnels)
        if not self.test():
            return False
        return self.reload()
